"""create_notifications

Revision: 542b6f363264
Revises: 5a1eb87f963d
Created: 2015-02-12 10:22:24.552198
"""

revision = '542b6f363264'
down_revision = '5a1eb87f963d'

from alembic import op
from spire.schema.fields import *
from sqlalchemy import Column, ForeignKey, ForeignKeyConstraint, PrimaryKeyConstraint, CheckConstraint
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    Column('id', UUIDType(), nullable=False),
    Column('created', DateTimeType(), nullable=False),
    Column('status', EnumerationType(), nullable=False),
    Column('resource', SurrogateType(), nullable=False),
    Column('ownerid', TokenType(), nullable=True),
    Column('type', TokenType(), nullable=False),
    Column('entity', TokenType(), nullable=False),
    PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    ### end Alembic commands ###
