"""add_owner

Revision: 5a1eb87f963d
Revises: None
Created: 2013-06-03 03:52:17.796150
"""

revision = '5a1eb87f963d'
down_revision = None

from alembic import op
from spire.schema.fields import *
from sqlalchemy import Column, ForeignKey, ForeignKeyConstraint, PrimaryKeyConstraint, CheckConstraint
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', Column('owner', TextType(), nullable=False))
    op.create_index('entry_owner_idx', 'entry', ['owner'])
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'owner')
    ### end Alembic commands ###
