"""create_notifications

Revision: 542b6f363264
Revises: 5a1eb87f963d
Created: 2015-02-12 10:22:24.552198
"""

revision = '66dedc931ef5'
down_revision = '542b6f363264'

from alembic import op
from spire.schema.fields import *
from sqlalchemy import Column, ForeignKey, ForeignKeyConstraint, PrimaryKeyConstraint, CheckConstraint
from sqlalchemy.dialects import postgresql
from spire.mesh import SurrogateType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('notification_ownerid_idx', 'notification', ['ownerid'])
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('notification_ownerid_idx')
    ### end Alembic commands ###
