"""create_notifications

Revision: 542b6f363264
Revises: 5a1eb87f963d
Created: 2015-02-12 10:22:24.552198
"""

revision = '7d8d1662e7bd'
down_revision = '66dedc931ef5'

from alembic import op
from spire.schema.fields import *
from sqlalchemy import Column, ForeignKey, ForeignKeyConstraint, PrimaryKeyConstraint, CheckConstraint
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE notification ADD read boolean")
    op.execute("update notification set read=false where status='unread'")
    op.execute("update notification set read=true where status='read'")
    op.execute("ALTER TABLE notification drop column status")
    op.create_index('notification_read_idx', 'notification', ['read'])
    ### end Alembic commands ###
def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE notification ADD status text")
    op.execute("update notification set status='unread' where read=false")
    op.execute("update notification set status='read' where read=true")
    op.execute("ALTER TABLE notification drop column read")
    op.drop_index('notification_read_idx')
    ### end Alembic commands ###
